services:
  jupyter-tae:
    image: jupyter/datascience-notebook:latest
    container_name: tae_environment
    ports:
      # Mapeamento: <Porta_Host>:<Porta_Contêiner>
      - "8889:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
    user: root
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
